package gemini

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestPackageInitialization(t *testing.T) {
	t.Parallel()
	// Basic test to ensure package compiles and initializes
	assert.True(t, true)
}

func TestAgentType(t *testing.T) {
	t.Parallel()
	// Test that agent type is defined
	assert.NotEmpty(t, "gemini")
}

// writeFakeGemini writes an executable fake `gemini` binary that emits the
// real CLI's JSON envelope ({"response": "<sentinel> ..."}) so a test can prove
// the integration genuinely exec'd it AND parsed its JSON output (real os/exec
// + extractGeminiText) rather than fabricating a templated response.
func writeFakeGemini(t *testing.T, sentinel string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("SKIP-OK: fake-binary injection uses a POSIX shell script")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "fake-gemini")
	// Emits a JSON object whose response field carries the sentinel.
	script := "#!/bin/sh\nprintf '{\"response\": \"" + sentinel + " from fake gemini\"}'\n"
	require.NoError(t, os.WriteFile(bin, []byte(script), 0o755))
	return bin
}

// TestGemini_RealExec is the §11.4.115 RED→GREEN guard for DEFECT D-17 /
// BLUFF-001 in this package. The original source fabricated "Gemini: <msg>" /
// "// Generated by Gemini" / "Code review by Gemini" with NO process execution.
// This guard injects a fake gemini binary via GEMINI_BIN and asserts the
// binary's real JSON `response` flows through to the result — proving real
// os/exec + JSON parsing is wired. §1.1 paired mutation: revert any handler to
// a hardcoded string → the sentinel disappears → this FAILs.
func TestGemini_RealExec(t *testing.T) {
	sentinel := "GEMINI_REAL_EXEC_SENTINEL_4Z"
	bin := writeFakeGemini(t, sentinel)
	t.Setenv("GEMINI_BIN", bin)

	g := New()
	ctx := context.Background()
	require.NoError(t, g.Initialize(ctx, nil))

	cases := []struct {
		command string
		params  map[string]interface{}
		field   string
	}{
		{"chat", map[string]interface{}{"message": "hi"}, "response"},
		{"generate", map[string]interface{}{"prompt": "x"}, "code"},
		{"explain", map[string]interface{}{"code": "func main(){}"}, "explanation"},
		{"review", map[string]interface{}{"code": "func main(){}"}, "review"},
	}
	for _, c := range cases {
		res, err := g.Execute(ctx, c.command, c.params)
		require.NoError(t, err, c.command)
		m := res.(map[string]interface{})
		assert.Contains(t, m[c.field].(string), sentinel,
			"%s must surface REAL gemini stdout (proving os/exec + JSON parse), not a fabricated string", c.command)
	}
}

// TestGemini_HonestErrorWhenBinaryAbsent proves that when no gemini binary is
// resolvable, the integration returns an honest error rather than a fabricated
// success (BLUFF-001).
func TestGemini_HonestErrorWhenBinaryAbsent(t *testing.T) {
	t.Setenv("GEMINI_BIN", filepath.Join(t.TempDir(), "does-not-exist"))

	g := New()
	ctx := context.Background()
	require.NoError(t, g.Initialize(ctx, nil))

	res, err := g.Execute(ctx, "chat", map[string]interface{}{"message": "x"})
	require.Error(t, err)
	assert.Nil(t, res)
	assert.False(t, g.IsAvailable(), "IsAvailable must be false when gemini is absent")
}
