package jetbrainsai

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-17 STUB-BLUFF PIN GUARD — RED-on-broken-artifact + GREEN regression guard
// (§11.4.115 polarity switch / §11.4.135 standing guard)
//
// HISTORY: JetBrainsAI.complete/chat/generate/explain/test/docs USED to return
// FABRICATED literals ("// JetBrains AI completion", "JetBrains AI: <msg>",
// "// Generated by JetBrains AI", "Code explanation from JetBrains AI", …)
// WITHOUT any real backend (zero os/exec, zero HTTP) — a stub bluff per
// BLUFF-001 / CONST-035.
//
// FIX (D-17): JetBrains AI runs ONLY inside the IDE process; there is no
// headless CLI or public standalone API, so these AI commands return an HONEST
// error (ErrIDEOnly) rather than fabricating a response.
// ---------------------------------------------------------------------------

// TestD17_JetBrainsAI_NoFabricatedResponse — standing GREEN regression guard.
func TestD17_JetBrainsAI_NoFabricatedResponse(t *testing.T) {
	j := New()
	ctx := context.Background()

	cases := []struct {
		name   string
		invoke func() (interface{}, error)
	}{
		{"complete", func() (interface{}, error) {
			return j.complete(ctx, map[string]interface{}{"file": "a.go"})
		}},
		{"chat", func() (interface{}, error) {
			return j.chat(ctx, map[string]interface{}{"message": "Hello"})
		}},
		{"generate", func() (interface{}, error) {
			return j.generate(ctx, map[string]interface{}{"prompt": "Create class"})
		}},
		{"explain", func() (interface{}, error) {
			return j.explain(ctx, map[string]interface{}{"code": "x"})
		}},
		{"test", func() (interface{}, error) {
			return j.test(ctx, map[string]interface{}{"code": "x"})
		}},
		{"docs", func() (interface{}, error) {
			return j.docs(ctx, map[string]interface{}{"code": "x"})
		}},
	}
	for _, c := range cases {
		res, err := c.invoke()
		if err == nil {
			t.Fatalf("D17 REGRESSION: JetBrainsAI.%s returned success %v with no real backend — must return an honest error (BLUFF-001 reintroduced?).", c.name, res)
		}
		if !errors.Is(err, ErrIDEOnly) {
			t.Fatalf("D17: JetBrainsAI.%s error should wrap ErrIDEOnly, got: %v", c.name, err)
		}
	}
}

// TestD17_JetBrainsAI_GenerateIsStubBluff — §11.4.115 RED-on-broken-artifact, RED_MODE=1.
func TestD17_JetBrainsAI_GenerateIsStubBluff(t *testing.T) {
	if os.Getenv("RED_MODE") != "1" {
		t.Skip("SKIP-OK: D-17 — §11.4.115 RED-on-broken-artifact reproduction; runs only with RED_MODE=1. " +
			"The standing GREEN guard is TestD17_JetBrainsAI_NoFabricatedResponse.")
	}
	j := New()
	res, err := j.generate(context.Background(), map[string]interface{}{"prompt": "Create class"})
	if err != nil {
		return
	}
	m, _ := res.(map[string]interface{})
	if code, _ := m["code"].(string); strings.Contains(code, "Generated by JetBrains AI") {
		t.Fatalf("D17 BLUFF PINNED: JetBrainsAI.generate returned the templated literal %q without any real backend (BLUFF-001).", code)
	}
}
