package amazonq

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-17 BLUFF-001 DE-BLUFF PIN GUARD (§11.4.115 RED→GREEN / §11.4.135)
//
// HISTORY: AmazonQ.chat/generate/explain/transform/scan/docs USED to fabricate
// their output — chat returned fmt.Sprintf("Amazon Q: %s", message), generate a
// hardcoded "// Generated by Amazon Q" template, explain/scan/docs hardcoded
// strings — WITHOUT exec-ing any real Amazon Q CLI binary (zero os/exec):
// BLUFF-001 / CONST-035.
//
// FIX (D-17): every method now exec-s the real Amazon Q Developer CLI via
// exec.LookPath + exec.CommandContext (resolveAmazonQBinary + runAmazonQ,
// `q chat --no-interactive --trust-all-tools "<msg>"`, falling back to
// kiro-cli / amazon-q). Absent binary → honest error, never a fabricated reply.
// ---------------------------------------------------------------------------

func writeFakeAmazonQ(t *testing.T, marker string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("SKIP-OK: D-17 — POSIX shell-script fake binary; real-exec path is identical across platforms.")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "fake-q")
	script := "#!/bin/sh\nprintf '" + marker + ":%s' \"$*\"\n"
	if err := os.WriteFile(bin, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake q: %v", err)
	}
	return bin
}

// TestD17_AmazonQ_ExecsRealBinary is the standing GREEN guard.
func TestD17_AmazonQ_ExecsRealBinary(t *testing.T) {
	const marker = "FAKE_AMAZONQ_RAN_c33d"
	bin := writeFakeAmazonQ(t, marker)
	t.Setenv("AMAZONQ_BIN", bin)

	a := New()
	ctx := context.Background()

	res, err := a.chat(ctx, map[string]interface{}{"message": "what is 2+2?"})
	if err != nil {
		t.Fatalf("chat returned error with fake binary injected: %v", err)
	}
	m, _ := res.(map[string]interface{})
	reply, _ := m["response"].(string)
	if !strings.Contains(reply, marker) {
		t.Fatalf("D17 REGRESSION: AmazonQ.chat did NOT exec the q binary — marker %q absent from %q.", marker, reply)
	}
	if strings.HasPrefix(reply, "Amazon Q: ") {
		t.Fatalf("D17 REGRESSION: AmazonQ.chat returned the echo template %q instead of real process output.", reply)
	}
	if !strings.Contains(reply, "what is 2+2?") {
		t.Fatalf("D17 REGRESSION: prompt not forwarded to the q binary (got %q).", reply)
	}

	gres, err := a.generate(ctx, map[string]interface{}{"prompt": "return 42", "language": "go"})
	if err != nil {
		t.Fatalf("generate returned error with fake binary injected: %v", err)
	}
	gm, _ := gres.(map[string]interface{})
	code, _ := gm["code"].(string)
	if !strings.Contains(code, marker) {
		t.Fatalf("D17 REGRESSION: AmazonQ.generate did NOT exec the q binary — marker %q absent from %q.", marker, code)
	}
	if strings.Contains(code, "// Generated by Amazon Q") {
		t.Fatalf("D17 REGRESSION: AmazonQ.generate returned the templated literal (got %q).", code)
	}
}

// TestD17_AmazonQ_AbsentBinaryIsHonestError proves the absent-binary path is an
// honest error, never a fabricated success.
func TestD17_AmazonQ_AbsentBinaryIsHonestError(t *testing.T) {
	// Override to a non-existent absolute path so the real `q`/`kiro-cli` on the
	// host (if any) is bypassed and the honest-error path is exercised.
	t.Setenv("AMAZONQ_BIN", filepath.Join(t.TempDir(), "does-not-exist-q"))

	a := New()
	ctx := context.Background()

	for _, tc := range []struct {
		cmd    string
		params map[string]interface{}
	}{
		{"chat", map[string]interface{}{"message": "x"}},
		{"generate", map[string]interface{}{"prompt": "x"}},
		{"explain", map[string]interface{}{"code": "x"}},
		{"transform", map[string]interface{}{"code": "x", "target": "rust"}},
		{"scan", map[string]interface{}{"code": "x"}},
		{"docs", map[string]interface{}{"code": "x"}},
	} {
		if _, err := a.Execute(ctx, tc.cmd, tc.params); err == nil {
			t.Fatalf("D17 BLUFF: AmazonQ.%s returned success with NO q binary available — must return an honest error.", tc.cmd)
		}
	}
}

// TestD17_AmazonQ_IsStubBluff is the §11.4.115 RED-on-broken-artifact polarity
// (RED_MODE=1). §1.1 paired mutation: revert chat() to the "Amazon Q: %s"
// template → this test FAILs (it fabricates a reply despite no binary).
func TestD17_AmazonQ_IsStubBluff(t *testing.T) {
	if os.Getenv("RED_MODE") != "1" {
		t.Skip("SKIP-OK: D-17 — §11.4.115 RED-on-broken-artifact reproduction; runs only with RED_MODE=1. " +
			"Standing GREEN guard: TestD17_AmazonQ_ExecsRealBinary.")
	}
	t.Setenv("AMAZONQ_BIN", filepath.Join(t.TempDir(), "does-not-exist-q"))

	a := New()
	ctx := context.Background()

	res, err := a.chat(ctx, map[string]interface{}{"message": "x"})
	if err != nil {
		return // FIXED artifact: honest error.
	}
	m, _ := res.(map[string]interface{})
	reply, _ := m["response"].(string)
	t.Fatalf("D17 BLUFF PINNED: AmazonQ.chat returned %q without exec-ing a real q binary (BLUFF-001).", reply)
}
