// Package speckit provides SpecKit agent integration.
// SpecKit (github/spec-kit): a Spec-Driven-Development toolkit whose `specify`
// CLI SCAFFOLDS a project (`specify init <name>`) and installs slash-command
// templates; the actual specification text is generated by a SEPARATE coding
// agent (Copilot / Claude / Gemini) responding to a `/specify` slash command —
// NOT by a headless `specify <requirement> -> spec-text` CLI call. The integration
// therefore exec-s the real `specify` binary for what it CAN do (project
// scaffolding) and returns an HONEST error for the requirement->spec-text
// "generate" semantic, which has no corresponding headless CLI capability.
// See https://github.com/github/spec-kit and https://github.github.com/spec-kit/ .
package speckit

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"strings"

	"dev.helix.agent/internal/clis/agents"
	"dev.helix.agent/internal/clis/agents/base"
)

// specifyBinary is the SpecKit CLI executable looked up on PATH. Overridable in
// tests via SPECIFY_BIN so a fake binary can be injected to prove real exec is
// wired (anti-bluff, BLUFF-001).
const specifyBinary = "specify"

// getSpecifyBinOverride returns the test-only specify binary override, if set.
func getSpecifyBinOverride() string { return os.Getenv("SPECIFY_BIN") }

// SpecKit provides SpecKit integration
type SpecKit struct {
	*base.BaseIntegration
	config *Config
}

// Config holds configuration
type Config struct {
	base.BaseConfig
	Format      string
	Integration string
}

// New creates a new SpecKit integration
func New() *SpecKit {
	info := agents.AgentInfo{
		Type:        agents.TypeSpecKit,
		Name:        "SpecKit",
		Description: "Spec-Driven-Development toolkit",
		Vendor:      "GitHub",
		Version:     "1.0.0",
		Capabilities: []string{
			"project_scaffolding",
			"spec_driven_development",
		},
		IsEnabled: true,
		Priority:  2,
	}

	return &SpecKit{
		BaseIntegration: base.NewBaseIntegration(info),
		config: &Config{
			BaseConfig: base.BaseConfig{
				AutoStart: true,
			},
			Format:      "markdown",
			Integration: "copilot",
		},
	}
}

// Initialize initializes SpecKit
func (s *SpecKit) Initialize(ctx context.Context, config interface{}) error {
	if err := s.BaseIntegration.Initialize(ctx, config); err != nil {
		return err
	}

	if cfg, ok := config.(*Config); ok {
		s.config = cfg
	}

	return nil
}

// Execute executes a command
func (s *SpecKit) Execute(ctx context.Context, command string, params map[string]interface{}) (interface{}, error) {
	if !s.IsStarted() {
		if err := s.Start(ctx); err != nil {
			return nil, err
		}
	}

	switch command {
	case "init":
		return s.initProject(ctx, params)
	case "generate":
		return s.generate(ctx, params)
	case "status":
		return s.status(ctx)
	default:
		return nil, fmt.Errorf("unknown command: %s", command)
	}
}

// resolveSpecifyBinary locates the specify CLI executable. Tests may inject a
// fake binary via SPECIFY_BIN (absolute path); otherwise the real `specify`
// command is resolved on PATH. Returns an honest error when absent — NEVER a
// fabricated success (BLUFF-001).
func (s *SpecKit) resolveSpecifyBinary() (string, error) {
	if bin := getSpecifyBinOverride(); bin != "" {
		if _, err := exec.LookPath(bin); err != nil {
			return "", fmt.Errorf("specify binary override %q not executable: %w", bin, err)
		}
		return bin, nil
	}
	path, err := exec.LookPath(specifyBinary)
	if err != nil {
		return "", fmt.Errorf("specify CLI not found on PATH: %w", err)
	}
	return path, nil
}

// initProject scaffolds a Spec-Driven-Development project by exec-ing the real
// `specify init <name> --integration <agent>` command. Returns the CLI's real
// output, or an honest error when the binary is absent / the command fails.
func (s *SpecKit) initProject(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	name, _ := params["name"].(string)
	if name == "" {
		return nil, fmt.Errorf("name required")
	}

	bin, err := s.resolveSpecifyBinary()
	if err != nil {
		return nil, err
	}

	args := []string{"init", name}
	if s.config.Integration != "" {
		args = append(args, "--integration", s.config.Integration)
	}

	cmd := exec.CommandContext(ctx, bin, args...)
	cmd.Dir = s.GetWorkDir()

	out, err := cmd.CombinedOutput()
	if err != nil {
		return nil, fmt.Errorf("specify init execution failed: %w (output: %s)", err, strings.TrimSpace(string(out)))
	}

	return map[string]interface{}{
		"name":        name,
		"output":      strings.TrimSpace(string(out)),
		"integration": s.config.Integration,
	}, nil
}

// generate returns an HONEST error: the spec-kit `specify` CLI has NO headless
// "turn a requirement string into specification text" command. Spec text is
// produced by a separate coding agent (Copilot/Claude/Gemini) responding to the
// `/specify` slash command installed by `specify init`. Fabricating a spec here
// would be a BLUFF-001 violation, so we direct the caller to the real path
// (scaffold via `init`, then drive the configured agent's `/specify` command)
// instead of returning a placeholder.
func (s *SpecKit) generate(ctx context.Context, params map[string]interface{}) (interface{}, error) {
	requirement, _ := params["requirement"].(string)
	if requirement == "" {
		return nil, fmt.Errorf("requirement required")
	}
	// Confirm the real CLI exists so the error distinguishes "tool missing" from
	// "tool present but capability is agent-driven, not headless".
	if _, err := s.resolveSpecifyBinary(); err != nil {
		return nil, err
	}
	return nil, fmt.Errorf("spec-kit has no headless requirement-to-spec command: "+
		"specification text is generated by the configured coding agent (%s) via the "+
		"`/specify` slash command after `specify init`; scaffold with Execute(\"init\", …) "+
		"then drive that agent — refusing to fabricate spec text (BLUFF-001)", s.config.Integration)
}

// status returns status
func (s *SpecKit) status(ctx context.Context) (interface{}, error) {
	return map[string]interface{}{
		"available":   s.IsAvailable(),
		"format":      s.config.Format,
		"integration": s.config.Integration,
	}, nil
}

// IsAvailable reports whether the real specify CLI is resolvable on PATH (or via
// the SPECIFY_BIN override). Honest availability — not a hardcoded true.
func (s *SpecKit) IsAvailable() bool {
	_, err := s.resolveSpecifyBinary()
	return err == nil
}

var _ agents.AgentIntegration = (*SpecKit)(nil)
