package kimi

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-17 STUB-BLUFF PIN GUARD — RED-on-broken-artifact + GREEN regression guard
// (§11.4.115 polarity switch / §11.4.120 reconcile / §11.4.135 standing guard)
//
// HISTORY (the bluff this guard catches): Kimi.chat / generate / analyze USED to
// return FABRICATED LITERAL strings ("Kimi: <message>", "// Generated by Kimi\n
// // <prompt>", "Document analysis by Kimi") WITHOUT ever exec-ing the real
// `kimi` CLI (zero os/exec in kimi.go) — a stub bluff per BLUFF-001 / CONST-035:
// the agent claimed to chat/generate/analyze with a model while running nothing.
//
// FIX (D-17): chat/generate/analyze now exec the real kimi CLI via
// exec.LookPath + exec.CommandContext (resolveKimiBinary + runKimi). When the
// binary is absent they return an HONEST error, never a fabricated success.
//
// This guard proves REAL exec is wired by injecting a FAKE kimi binary on PATH
// (KIMI_BIN override) whose stdout is an unforgeable marker, then asserting the
// fabricated literals are NEVER returned. GREEN by default; reverting any method
// to its templated-string form makes the marker absent / the literal present →
// this guard FAILs. Standing regression guard for D-17 (§11.4.135).
//
// The historical RED polarity (assert the stub literal IS present on the pre-fix
// artifact) is preserved under RED_MODE=1 for §11.4.115 reproduce-on-broken.
// ---------------------------------------------------------------------------

// writeFakeKimi creates an executable shell script that echoes a JSON envelope
// whose "response" field embeds the unforgeable marker plus the prompt it was
// invoked with, then returns its absolute path. Skips on non-POSIX hosts.
func writeFakeKimi(t *testing.T, marker string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("SKIP-OK: D-17 — fake-binary injection uses a POSIX shell script; " +
			"not portable to Windows. The real-exec code path is identical across platforms.")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "fake-kimi")
	script := "#!/bin/sh\nprintf '{\"response\":\"" + marker + ":%s\"}' \"$*\"\n"
	if err := os.WriteFile(bin, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake kimi: %v", err)
	}
	return bin
}

// TestD17_Kimi_ExecsRealBinary is the standing GREEN regression guard.
func TestD17_Kimi_ExecsRealBinary(t *testing.T) {
	const marker = "FAKE_KIMI_RAN_2f9c"
	bin := writeFakeKimi(t, marker)
	t.Setenv("KIMI_BIN", bin)

	k := New()
	ctx := context.Background()

	gres, err := k.generate(ctx, map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		t.Fatalf("generate returned error with fake binary injected: %v", err)
	}
	gm, _ := gres.(map[string]interface{})
	code, _ := gm["code"].(string)
	if !strings.Contains(code, marker) {
		t.Fatalf("D17 REGRESSION: Kimi.generate did NOT exec the kimi binary — marker %q absent from %q (BLUFF-001?).", marker, code)
	}
	if strings.HasPrefix(code, "// Generated by Kimi") {
		t.Fatalf("D17 REGRESSION: Kimi.generate returned the templated literal %q instead of real process output.", code)
	}
	if !strings.Contains(code, "return the number 42 in Go") {
		t.Fatalf("D17 REGRESSION: prompt was not forwarded to the kimi binary (got %q).", code)
	}

	cres, err := k.chat(ctx, map[string]interface{}{"message": "what is 2+2?"})
	if err != nil {
		t.Fatalf("chat returned error with fake binary injected: %v", err)
	}
	cm, _ := cres.(map[string]interface{})
	reply, _ := cm["response"].(string)
	if !strings.Contains(reply, marker) {
		t.Fatalf("D17 REGRESSION: Kimi.chat did NOT exec the kimi binary — marker %q absent from %q.", marker, reply)
	}
	if strings.HasPrefix(reply, "Kimi: ") {
		t.Fatalf("D17 REGRESSION: Kimi.chat returned the echo template %q instead of a real model reply.", reply)
	}
}

// TestD17_Kimi_AbsentBinaryIsHonestError proves the absent-binary path returns
// an honest error, never a fabricated success.
func TestD17_Kimi_AbsentBinaryIsHonestError(t *testing.T) {
	t.Setenv("KIMI_BIN", filepath.Join(t.TempDir(), "does-not-exist-kimi"))

	k := New()
	ctx := context.Background()

	if _, err := k.generate(ctx, map[string]interface{}{"prompt": "x"}); err == nil {
		t.Fatal("D17 BLUFF: generate returned success with NO kimi binary available — must be an honest error.")
	}
	if _, err := k.chat(ctx, map[string]interface{}{"message": "x"}); err == nil {
		t.Fatal("D17 BLUFF: chat returned success with NO kimi binary available — must be an honest error.")
	}
	if _, err := k.analyze(ctx, map[string]interface{}{"document": "x"}); err == nil {
		t.Fatal("D17 BLUFF: analyze returned success with NO kimi binary available — must be an honest error.")
	}
}

// TestD17_Kimi_GenerateIsStubBluff is the §11.4.115 RED-on-broken-artifact
// reproduction, runnable ONLY under RED_MODE=1. On the pre-fix STUB artifact it
// FAILs (the templated literal IS returned); on the fixed artifact it returns
// an honest error (no binary) so the bluff is provably gone.
func TestD17_Kimi_GenerateIsStubBluff(t *testing.T) {
	if os.Getenv("RED_MODE") != "1" {
		t.Skip("SKIP-OK: D-17 — §11.4.115 RED-on-broken-artifact reproduction; runs only with RED_MODE=1. " +
			"The standing GREEN guard is TestD17_Kimi_ExecsRealBinary.")
	}

	k := New()
	ctx := context.Background()

	res, err := k.generate(ctx, map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		// Fixed artifact, no binary: honest error — bluff is gone.
		return
	}
	m, _ := res.(map[string]interface{})
	code, _ := m["code"].(string)
	if strings.HasPrefix(code, "// Generated by Kimi") {
		t.Fatalf("D17 BLUFF PINNED: Kimi.generate returned the templated literal %q without exec-ing the real kimi binary (BLUFF-001).", code)
	}
}
