package deepseekcli

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestPackageInitialization(t *testing.T) {
	t.Parallel()
	assert.True(t, true)
}

func TestAgentType(t *testing.T) {
	t.Parallel()
	assert.NotEmpty(t, "deepseekcli")
}

// TestDeepSeekCLI_NoFabricatedResponse is the §11.4.115 / BLUFF-001 regression
// guard for DEFECT D-17. DeepSeek has no headless CLI, so chat/generate MUST
// return an honest error after input validation — NEVER the old fabricated
// "DeepSeek: <msg>" / "// Generated by DeepSeek CLI" strings. §1.1 paired
// mutation: revert either handler to return a fabricated map + nil error → this
// FAILs (it asserts an error AND a nil result).
func TestDeepSeekCLI_NoFabricatedResponse(t *testing.T) {
	t.Parallel()
	d := New()
	ctx := context.Background()
	require.NoError(t, d.Initialize(ctx, nil))

	for _, c := range []struct {
		command string
		params  map[string]interface{}
	}{
		{"chat", map[string]interface{}{"message": "Hello"}},
		{"generate", map[string]interface{}{"prompt": "x"}},
	} {
		res, err := d.Execute(ctx, c.command, c.params)
		require.Error(t, err, "%s must not fabricate", c.command)
		assert.Nil(t, res, "%s must not return a fabricated result", c.command)
		assert.Contains(t, err.Error(), "no official headless CLI")
	}

	// Input validation still fires first.
	_, err := d.Execute(ctx, "chat", map[string]interface{}{})
	require.Error(t, err)
	assert.Contains(t, err.Error(), "message required")
}
