package junie

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-17 STUB-BLUFF PIN GUARD — RED-on-broken-artifact + GREEN regression guard
// (§11.4.115 polarity switch / §11.4.135 standing guard)
//
// HISTORY: Junie.generate USED to return the FABRICATED literal
// "// Generated by Junie\n// <prompt>" and Junie.complete "// Junie completion"
// WITHOUT exec-ing anything (zero os/exec in junie.go) — a stub bluff per
// BLUFF-001 / CONST-035.
//
// FIX (D-17): generate/complete now exec the real `junie --non-interactive` CLI
// (resolveJunieBinary + runJunie); honest error when the binary is absent.
// ---------------------------------------------------------------------------

func writeFakeJunie(t *testing.T, marker string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("SKIP-OK: D-17 — fake-binary injection uses a POSIX shell script; not portable to Windows.")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "fake-junie")
	script := "#!/bin/sh\nprintf '" + marker + ":%s' \"$*\"\n"
	if err := os.WriteFile(bin, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake junie: %v", err)
	}
	return bin
}

// TestD17_Junie_ExecsRealBinary — standing GREEN regression guard.
func TestD17_Junie_ExecsRealBinary(t *testing.T) {
	const marker = "FAKE_JUNIE_RAN_5c2d"
	bin := writeFakeJunie(t, marker)
	t.Setenv("JUNIE_BIN", bin)

	j := New()
	ctx := context.Background()

	gres, err := j.generate(ctx, map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		t.Fatalf("generate returned error with fake binary injected: %v", err)
	}
	gm, _ := gres.(map[string]interface{})
	code, _ := gm["code"].(string)
	if !strings.Contains(code, marker) {
		t.Fatalf("D17 REGRESSION: Junie.generate did NOT exec the junie binary — marker %q absent from %q (BLUFF-001?).", marker, code)
	}
	if strings.HasPrefix(code, "// Generated by Junie") {
		t.Fatalf("D17 REGRESSION: Junie.generate returned the templated literal %q instead of real process output.", code)
	}
	if !strings.Contains(code, "return the number 42 in Go") {
		t.Fatalf("D17 REGRESSION: prompt was not forwarded to the junie binary (got %q).", code)
	}

	cres, err := j.complete(ctx, map[string]interface{}{"code": "func add(a, b int) int {"})
	if err != nil {
		t.Fatalf("complete returned error with fake binary injected: %v", err)
	}
	cm, _ := cres.(map[string]interface{})
	completion, _ := cm["completion"].(string)
	if !strings.Contains(completion, marker) {
		t.Fatalf("D17 REGRESSION: Junie.complete did NOT exec the junie binary — marker %q absent from %q.", marker, completion)
	}
	if completion == "// Junie completion" {
		t.Fatalf("D17 REGRESSION: Junie.complete returned the fabricated literal instead of real output.")
	}
}

// TestD17_Junie_AbsentBinaryIsHonestError — absent binary ⇒ honest error.
func TestD17_Junie_AbsentBinaryIsHonestError(t *testing.T) {
	t.Setenv("JUNIE_BIN", filepath.Join(t.TempDir(), "does-not-exist-junie"))
	j := New()
	ctx := context.Background()
	if _, err := j.generate(ctx, map[string]interface{}{"prompt": "x"}); err == nil {
		t.Fatal("D17 BLUFF: generate returned success with NO junie binary available — must be an honest error.")
	}
	if _, err := j.complete(ctx, map[string]interface{}{"code": "x"}); err == nil {
		t.Fatal("D17 BLUFF: complete returned success with NO junie binary available — must be an honest error.")
	}
}

// TestD17_Junie_GenerateIsStubBluff — §11.4.115 RED-on-broken-artifact, RED_MODE=1.
func TestD17_Junie_GenerateIsStubBluff(t *testing.T) {
	if os.Getenv("RED_MODE") != "1" {
		t.Skip("SKIP-OK: D-17 — §11.4.115 RED-on-broken-artifact reproduction; runs only with RED_MODE=1. " +
			"The standing GREEN guard is TestD17_Junie_ExecsRealBinary.")
	}
	j := New()
	res, err := j.generate(context.Background(), map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		return
	}
	m, _ := res.(map[string]interface{})
	code, _ := m["code"].(string)
	if strings.HasPrefix(code, "// Generated by Junie") {
		t.Fatalf("D17 BLUFF PINNED: Junie.generate returned the templated literal %q without exec-ing the real junie binary (BLUFF-001).", code)
	}
}
