package hunyuan

import (
	"context"
	"errors"
	"os"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-17 STUB-BLUFF PIN GUARD — RED-on-broken-artifact + GREEN regression guard
// (§11.4.115 polarity switch / §11.4.135 standing guard)
//
// HISTORY: Hunyuan.chat USED to return the FABRICATED literal "Hunyuan: <msg>"
// and Hunyuan.generate "// Generated by Hunyuan\n// <prompt>" WITHOUT any real
// backend call (zero os/exec, zero HTTP in hunyuan.go) — a stub bluff per
// BLUFF-001 / CONST-035.
//
// FIX (D-17): Hunyuan has NO headless CLI; the real Tencent Cloud HTTP client is
// not wired, so chat/generate return an HONEST error (ErrNoBackend) rather than
// fabricating a response. This is the honest-error path mandated for no-CLI
// agents — never a fabricated success.
// ---------------------------------------------------------------------------

// TestD17_Hunyuan_NoFabricatedResponse — standing GREEN regression guard.
func TestD17_Hunyuan_NoFabricatedResponse(t *testing.T) {
	h := New()
	ctx := context.Background()

	cres, cerr := h.chat(ctx, map[string]interface{}{"message": "Hello"})
	if cerr == nil {
		t.Fatalf("D17 REGRESSION: Hunyuan.chat returned success %v with no real backend — it must return an honest error (BLUFF-001 reintroduced?).", cres)
	}
	if !errors.Is(cerr, ErrNoBackend) {
		t.Fatalf("D17: Hunyuan.chat error should wrap ErrNoBackend, got: %v", cerr)
	}
	if strings.Contains(cerr.Error(), "Hunyuan: Hello") {
		t.Fatalf("D17 REGRESSION: Hunyuan.chat fabricated the templated reply.")
	}

	gres, gerr := h.generate(ctx, map[string]interface{}{"prompt": "Create function"})
	if gerr == nil {
		t.Fatalf("D17 REGRESSION: Hunyuan.generate returned success %v with no real backend — it must return an honest error.", gres)
	}
	if !errors.Is(gerr, ErrNoBackend) {
		t.Fatalf("D17: Hunyuan.generate error should wrap ErrNoBackend, got: %v", gerr)
	}
}

// TestD17_Hunyuan_GenerateIsStubBluff — §11.4.115 RED-on-broken-artifact, RED_MODE=1.
func TestD17_Hunyuan_GenerateIsStubBluff(t *testing.T) {
	if os.Getenv("RED_MODE") != "1" {
		t.Skip("SKIP-OK: D-17 — §11.4.115 RED-on-broken-artifact reproduction; runs only with RED_MODE=1. " +
			"The standing GREEN guard is TestD17_Hunyuan_NoFabricatedResponse.")
	}
	h := New()
	res, err := h.generate(context.Background(), map[string]interface{}{"prompt": "Create function"})
	if err != nil {
		// Fixed artifact: honest error — bluff is gone.
		return
	}
	m, _ := res.(map[string]interface{})
	if code, _ := m["code"].(string); strings.HasPrefix(code, "// Generated by Hunyuan") {
		t.Fatalf("D17 BLUFF PINNED: Hunyuan.generate returned the templated literal %q without any real backend call (BLUFF-001).", code)
	}
}
