// Package mistralcode provides tests for Mistral Code agent integration
package mistralcode

import (
	"context"
	"testing"

	"dev.helix.agent/internal/clis/agents"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNewMistralCode(t *testing.T) {
	t.Parallel()
	m := New()
	require.NotNil(t, m)

	info := m.Info()
	assert.Equal(t, agents.TypeMistralCode, info.Type)
	assert.Equal(t, "Mistral Code", info.Name)
	assert.Equal(t, "Mistral AI", info.Vendor)
	assert.True(t, info.IsEnabled)
}

// TestMistralCodeHonestErrors reconciled (§11.4.120 / §11.4.115): generate /
// complete / chat used to return TEMPLATED literals ("// Generated by Mistral",
// "// Mistral completion", "Mistral: <msg>") without any real backend — a
// BLUFF-001/003 stub. Mistral Code ships as an IDE extension, not a headless
// CLI, so with no real backend wired these MUST return the honest ErrNoBackend.
// This is the standing GREEN guard for D-17 — reverting to a fabricated map
// makes it FAIL.
func TestMistralCodeHonestErrors(t *testing.T) {
	t.Parallel()
	m := New()
	ctx := context.Background()
	require.NoError(t, m.Initialize(ctx, nil))

	gres, gerr := m.Execute(ctx, "generate", map[string]interface{}{"prompt": "x"})
	require.ErrorIs(t, gerr, ErrNoBackend,
		"generate must return the honest no-backend error, never a fabricated template")
	assert.Nil(t, gres)

	cres, cerr := m.Execute(ctx, "complete", map[string]interface{}{"prefix": "func "})
	require.ErrorIs(t, cerr, ErrNoBackend,
		"complete must return the honest no-backend error, never a fabricated completion")
	assert.Nil(t, cres)

	chres, cherr := m.Execute(ctx, "chat", map[string]interface{}{"message": "hi"})
	require.ErrorIs(t, cherr, ErrNoBackend,
		"chat must return the honest no-backend error, never a fabricated reply")
	assert.Nil(t, chres)
}

// TestMistralCodeRequiredParams: missing-param validation still fires before the
// honest-error path (so the user gets the clearer error).
func TestMistralCodeRequiredParams(t *testing.T) {
	t.Parallel()
	m := New()
	ctx := context.Background()
	require.NoError(t, m.Initialize(ctx, nil))

	for _, cmd := range []string{"generate", "complete", "chat"} {
		_, err := m.Execute(ctx, cmd, map[string]interface{}{})
		assert.Error(t, err, "%s with no params must error", cmd)
	}
}

// TestMistralCodeStatus: status remains a non-fabricating metadata command.
func TestMistralCodeStatus(t *testing.T) {
	t.Parallel()
	m := New()
	ctx := context.Background()
	require.NoError(t, m.Initialize(ctx, nil))

	res, err := m.Execute(ctx, "status", nil)
	require.NoError(t, err)
	resMap, ok := res.(map[string]interface{})
	require.True(t, ok)
	assert.Contains(t, resMap, "available")
	assert.Equal(t, "codestral-latest", resMap["model"])
}
