package qwencode

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-6 STUB-BLUFF PIN GUARD — RECONCILED TO GREEN POLARITY (§11.4.115 / §11.4.120)
//
// HISTORY (the bluff this guard catches): QwenCode.generate / complete / chat
// USED to return TEMPLATED LITERAL strings ("// Generated by Qwen\n// <prompt>",
// "// Qwen completion", "Qwen: <message>") WITHOUT ever exec-ing the real `qwen`
// CLI binary (zero os/exec in qwencode.go) — a stub bluff per BLUFF-001/003 /
// CONST-035: the agent claimed to generate code while running nothing.
//
// FIX (SP4): generate/complete/chat now exec the real qwen CLI via
// exec.LookPath + exec.CommandContext (resolveQwenBinary + runQwen). When the
// binary is absent they return an HONEST error, never a fabricated success.
//
// This guard proves REAL exec is wired by injecting a FAKE qwen binary on PATH
// (QWEN_BIN override) whose stdout is an unforgeable marker, then asserting:
//   (a) generate/chat return the fake binary's REAL stdout (proves exec ran), AND
//   (b) the old templated literals are NEVER returned (FAILs if reverted to stub).
// Reverting any method to its templated-string form makes the marker absent and
// the literal present → this guard FAILs. It is GREEN by default (no env gate)
// and is the standing regression guard for D-6 (§11.4.135).
//
// The historical RED polarity (assert the stub literal IS present on the pre-fix
// artifact) is preserved under PIN_STUB_BLUFF=1 for §11.4.115 reproduce-on-broken.
// ---------------------------------------------------------------------------

// writeFakeQwen creates an executable shell script that echoes a JSON envelope
// whose "response" field embeds the unforgeable marker plus the prompt it was
// invoked with, then returns its absolute path. Skips on non-POSIX hosts.
func writeFakeQwen(t *testing.T, marker string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("SKIP-OK: ATM-SP2-D6 — fake-binary injection uses a POSIX shell script; " +
			"not portable to Windows. The real-exec code path is identical across platforms.")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "fake-qwen")
	// The fake prints a JSON object on stdout: {"response":"<marker>:<args...>"}.
	// "$*" captures all args so we can prove the prompt was forwarded.
	script := "#!/bin/sh\nprintf '{\"response\":\"" + marker + ":%s\"}' \"$*\"\n"
	if err := os.WriteFile(bin, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake qwen: %v", err)
	}
	return bin
}

func TestD6_QwenCode_GenerateExecsRealBinary(t *testing.T) {
	const marker = "FAKE_QWEN_RAN_2f9c"
	bin := writeFakeQwen(t, marker)
	t.Setenv("QWEN_BIN", bin)

	q := New()
	ctx := context.Background()

	// generate: must return the fake binary's REAL stdout, never the templated
	// "// Generated by Qwen\n// <prompt>" literal.
	res, err := q.generate(ctx, map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		t.Fatalf("generate returned error with fake binary injected: %v", err)
	}
	m, ok := res.(map[string]interface{})
	if !ok {
		t.Fatalf("expected map result, got %T", res)
	}
	code, _ := m["code"].(string)
	if !strings.Contains(code, marker) {
		t.Fatalf("D6 REGRESSION: QwenCode.generate did NOT exec the qwen binary — "+
			"its stdout marker %q is absent from the result %q (BLUFF-001 reintroduced?).", marker, code)
	}
	if strings.HasPrefix(code, "// Generated by Qwen") {
		t.Fatalf("D6 REGRESSION: QwenCode.generate returned the templated literal %q "+
			"instead of real process output (BLUFF-001 reintroduced).", code)
	}
	if !strings.Contains(code, "return the number 42 in Go") {
		t.Fatalf("D6 REGRESSION: prompt %q was not forwarded to the qwen binary (got %q).",
			"return the number 42 in Go", code)
	}

	// chat: must return the fake binary's REAL reply, never the "Qwen: <msg>" echo.
	cres, err := q.chat(ctx, map[string]interface{}{"message": "what is 2+2?"})
	if err != nil {
		t.Fatalf("chat returned error with fake binary injected: %v", err)
	}
	cm, _ := cres.(map[string]interface{})
	reply, _ := cm["response"].(string)
	if !strings.Contains(reply, marker) {
		t.Fatalf("D6 REGRESSION: QwenCode.chat did NOT exec the qwen binary — "+
			"its stdout marker %q is absent from the reply %q (BLUFF-003 reintroduced?).", marker, reply)
	}
	if strings.HasPrefix(reply, "Qwen: ") {
		t.Fatalf("D6 REGRESSION: QwenCode.chat returned the echo template %q "+
			"instead of a real model reply (BLUFF-003 reintroduced).", reply)
	}
}

// TestD6_QwenCode_AbsentBinaryIsHonestError proves that with NO qwen binary
// available the methods return an honest error (NOT a fabricated success) —
// the anti-bluff guarantee for the absent-binary path.
func TestD6_QwenCode_AbsentBinaryIsHonestError(t *testing.T) {
	// Point QWEN_BIN at a path that does not exist → resolveQwenBinary fails.
	t.Setenv("QWEN_BIN", filepath.Join(t.TempDir(), "does-not-exist-qwen"))

	q := New()
	ctx := context.Background()

	if _, err := q.generate(ctx, map[string]interface{}{"prompt": "x"}); err == nil {
		t.Fatal("D6 BLUFF: generate returned success with NO qwen binary available — " +
			"must return an honest error, never a fabricated template.")
	}
	if _, err := q.chat(ctx, map[string]interface{}{"message": "x"}); err == nil {
		t.Fatal("D6 BLUFF: chat returned success with NO qwen binary available — " +
			"must return an honest error, never a fabricated template.")
	}
}

// TestD6_QwenCode_GenerateIsStubBluff is the §11.4.115 RED-polarity reproduction
// of the historical bluff, runnable ONLY under PIN_STUB_BLUFF=1. On the pre-fix
// artifact it would FAIL (the stub literal IS returned); on the fixed artifact
// it is skipped (the standing GREEN guard above is the regression guard).
func TestD6_QwenCode_GenerateIsStubBluff(t *testing.T) {
	if os.Getenv("PIN_STUB_BLUFF") != "1" {
		t.Skip("SKIP-OK: ATM-SP2-D6 — §11.4.115 RED-on-broken-artifact reproduction; " +
			"runs only with PIN_STUB_BLUFF=1. The standing GREEN guard is " +
			"TestD6_QwenCode_GenerateExecsRealBinary.")
	}

	q := New()
	ctx := context.Background()

	// On the FIXED artifact (no binary injected) generate returns an honest error;
	// on the pre-fix STUB artifact it returned the templated literal. Either way,
	// the bluff (templated literal returned) must be ABSENT.
	res, err := q.generate(ctx, map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		// Fixed artifact, no binary: honest error — bluff is gone.
		return
	}
	m, _ := res.(map[string]interface{})
	code, _ := m["code"].(string)
	if strings.HasPrefix(code, "// Generated by Qwen") {
		t.Fatalf("D6 BLUFF PINNED: QwenCode.generate returned the templated literal %q without "+
			"exec-ing the real qwen binary (BLUFF-001).", code)
	}
}
