package qwencode

import (
	"context"
	"os"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-6 STUB-BLUFF PINNING GUARD (left RED on purpose — pin, do NOT fix here)
//
// QwenCode.generate / complete / chat return TEMPLATED LITERAL strings
// ("// Generated by Qwen\n// <prompt>", "// Qwen completion", "Qwen: <message>")
// WITHOUT ever exec-ing the real `qwen` CLI binary (zero os/exec in
// qwencode.go). This is a stub bluff per BLUFF-001/003 / CONST-035: the agent
// claims to generate code while running nothing.
//
// This test DOCUMENTS that defect. It is skipped by default so it does not block
// the standing suite; set PIN_STUB_BLUFF=1 to run it, at which point it FAILs on
// the current stub (proving the bluff is live). It becomes GREEN when SP4 wires
// real os/exec invocation of the qwen binary into these methods.
//
//   PIN_STUB_BLUFF=1 go test -run TestD6_QwenCode_GenerateIsStubBluff -v ./internal/clis/agents/qwencode
// ---------------------------------------------------------------------------

func TestD6_QwenCode_GenerateIsStubBluff(t *testing.T) {
	if os.Getenv("PIN_STUB_BLUFF") != "1" {
		t.Skip("SKIP-OK: ATM-SP2-D6 — defect-pinning guard for the QwenCode generate/complete/chat " +
			"stub bluff (BLUFF-001). Left RED on purpose; runs only with PIN_STUB_BLUFF=1. " +
			"Becomes GREEN when SP4 replaces the templated-string returns with a real os/exec of the qwen binary.")
	}

	q := New()
	ctx := context.Background()

	// generate: a real exec would produce the qwen binary's actual stdout, never
	// the fixed "// Generated by Qwen\n// <prompt>" template.
	res, err := q.generate(ctx, map[string]interface{}{"prompt": "return the number 42 in Go"})
	if err != nil {
		t.Fatalf("generate returned error: %v", err)
	}
	m, ok := res.(map[string]interface{})
	if !ok {
		t.Fatalf("expected map result, got %T", res)
	}
	code, _ := m["code"].(string)
	if strings.HasPrefix(code, "// Generated by Qwen") {
		t.Fatalf("D6 BLUFF PINNED: QwenCode.generate returned the templated literal %q without "+
			"exec-ing the real qwen binary (BLUFF-001). Expected real generated code from a process.", code)
	}

	// chat: a real exec would return the model's actual reply, never the fixed
	// "Qwen: <message>" echo template.
	cres, err := q.chat(ctx, map[string]interface{}{"message": "what is 2+2?"})
	if err != nil {
		t.Fatalf("chat returned error: %v", err)
	}
	cm, _ := cres.(map[string]interface{})
	reply, _ := cm["response"].(string)
	if strings.HasPrefix(reply, "Qwen: ") {
		t.Fatalf("D6 BLUFF PINNED: QwenCode.chat returned the echo template %q without exec-ing "+
			"the real qwen binary (BLUFF-001). Expected a real model reply.", reply)
	}
}
