package cody

import (
	"context"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// D-17 BLUFF-001 DE-BLUFF PIN GUARD (§11.4.115 RED→GREEN / §11.4.120 / §11.4.135)
//
// HISTORY (the bluff this guard catches): Cody.chat/explain/generate/search/
// review/edit/symbol USED to fabricate their responses — chat returned
// fmt.Sprintf("Cody: %s", message), generate returned a hardcoded
// "// Generated by Cody\n..." template, search/review/symbol returned hardcoded
// result maps — WITHOUT ever exec-ing the real `cody` CLI binary (zero os/exec
// in cody.go): a BLUFF-001 / CONST-035 violation. The agent claimed to run Cody
// while running nothing, and the old cody_test.go codified that bluff as PASS.
//
// FIX (D-17): every LLM-backed method now exec-s the real Sourcegraph Cody CLI
// via exec.LookPath + exec.CommandContext (resolveCodyBinary + runCody,
// `cody chat -m "<msg>"`). When the binary is absent they return an HONEST
// error, never a fabricated success.
//
// This guard proves REAL exec is wired by injecting a FAKE cody binary on PATH
// (CODY_BIN override) whose stdout is an unforgeable marker, then asserting the
// methods return that real stdout and NEVER the old fabricated literals. It is
// GREEN by default (RED_MODE=0) and is the standing regression guard (§11.4.135).
// ---------------------------------------------------------------------------

// writeFakeCody creates an executable shell script that echoes the unforgeable
// marker plus the args it was invoked with, then returns its absolute path.
func writeFakeCody(t *testing.T, marker string) string {
	t.Helper()
	if runtime.GOOS == "windows" {
		t.Skip("SKIP-OK: D-17 — fake-binary injection uses a POSIX shell script; " +
			"not portable to Windows. The real-exec code path is identical across platforms.")
	}
	dir := t.TempDir()
	bin := filepath.Join(dir, "fake-cody")
	script := "#!/bin/sh\nprintf '" + marker + ":%s' \"$*\"\n"
	if err := os.WriteFile(bin, []byte(script), 0o755); err != nil {
		t.Fatalf("write fake cody: %v", err)
	}
	return bin
}

// TestD17_Cody_ExecsRealBinary is the standing GREEN guard: with a fake cody
// binary injected, every LLM-backed method MUST return the binary's real stdout
// (proving exec ran) and MUST NOT return the old fabricated literals.
func TestD17_Cody_ExecsRealBinary(t *testing.T) {
	const marker = "FAKE_CODY_RAN_a71e"
	bin := writeFakeCody(t, marker)
	t.Setenv("CODY_BIN", bin)

	c := New()
	ctx := context.Background()

	// chat: real stdout, never the "Cody: <msg>" echo template.
	res, err := c.chat(ctx, map[string]interface{}{"message": "what is 2+2?"})
	if err != nil {
		t.Fatalf("chat returned error with fake binary injected: %v", err)
	}
	m, _ := res.(map[string]interface{})
	reply, _ := m["response"].(string)
	if !strings.Contains(reply, marker) {
		t.Fatalf("D17 REGRESSION: Cody.chat did NOT exec the cody binary — marker %q absent from %q (BLUFF-001 reintroduced?).", marker, reply)
	}
	if strings.HasPrefix(reply, "Cody: ") {
		t.Fatalf("D17 REGRESSION: Cody.chat returned the echo template %q instead of real process output (BLUFF-001 reintroduced).", reply)
	}
	if !strings.Contains(reply, "what is 2+2?") {
		t.Fatalf("D17 REGRESSION: prompt was not forwarded to the cody binary (got %q).", reply)
	}

	// generate: real stdout, never the "// Generated by Cody" template.
	gres, err := c.generate(ctx, map[string]interface{}{"prompt": "return 42", "language": "go"})
	if err != nil {
		t.Fatalf("generate returned error with fake binary injected: %v", err)
	}
	gm, _ := gres.(map[string]interface{})
	code, _ := gm["code"].(string)
	if !strings.Contains(code, marker) {
		t.Fatalf("D17 REGRESSION: Cody.generate did NOT exec the cody binary — marker %q absent from %q.", marker, code)
	}
	if strings.Contains(code, "// Generated by Cody") {
		t.Fatalf("D17 REGRESSION: Cody.generate returned the templated literal instead of real process output (got %q).", code)
	}

	// explain/review/search/edit/symbol all route through runCody — spot-check explain.
	eres, err := c.explain(ctx, map[string]interface{}{"code": "func main(){}"})
	if err != nil {
		t.Fatalf("explain returned error with fake binary injected: %v", err)
	}
	em, _ := eres.(map[string]interface{})
	expl, _ := em["explanation"].(string)
	if !strings.Contains(expl, marker) {
		t.Fatalf("D17 REGRESSION: Cody.explain did NOT exec the cody binary — marker %q absent from %q.", marker, expl)
	}
	if strings.Contains(expl, "This code") {
		t.Fatalf("D17 REGRESSION: Cody.explain returned the fabricated summary template (got %q).", expl)
	}
}

// TestD17_Cody_AbsentBinaryIsHonestError proves that with NO cody binary
// available the LLM-backed methods return an honest error, never a fabricated
// success — the anti-bluff guarantee for the absent-binary path.
func TestD17_Cody_AbsentBinaryIsHonestError(t *testing.T) {
	t.Setenv("CODY_BIN", filepath.Join(t.TempDir(), "does-not-exist-cody"))

	c := New()
	ctx := context.Background()

	for _, tc := range []struct {
		cmd    string
		params map[string]interface{}
	}{
		{"chat", map[string]interface{}{"message": "x"}},
		{"generate", map[string]interface{}{"prompt": "x"}},
		{"explain", map[string]interface{}{"code": "x"}},
		{"review", map[string]interface{}{"code": "x"}},
		{"search", map[string]interface{}{"query": "x"}},
		{"edit", map[string]interface{}{"file": "x", "instruction": "y"}},
		{"symbol", map[string]interface{}{"name": "x"}},
	} {
		if _, err := c.Execute(ctx, tc.cmd, tc.params); err == nil {
			t.Fatalf("D17 BLUFF: Cody.%s returned success with NO cody binary available — must return an honest error, never a fabricated response.", tc.cmd)
		}
	}
}

// TestD17_Cody_IsStubBluff is the §11.4.115 RED-on-broken-artifact reproduction,
// runnable ONLY under RED_MODE=1. On the PRE-FIX artifact (fabricating methods)
// it FAILs — the fabricated literal IS returned with NO binary present. On the
// FIXED artifact it PASSes (honest error, bluff absent). The §1.1 paired
// mutation: revert chat() to `fmt.Sprintf("Cody: %s", message)` and this test
// (RED_MODE=1) FAILs, while TestD17_Cody_AbsentBinaryIsHonestError also FAILs —
// proving the guard pair genuinely catches the bluff.
func TestD17_Cody_IsStubBluff(t *testing.T) {
	if os.Getenv("RED_MODE") != "1" {
		t.Skip("SKIP-OK: D-17 — §11.4.115 RED-on-broken-artifact reproduction; runs only with RED_MODE=1. " +
			"The standing GREEN guard is TestD17_Cody_ExecsRealBinary.")
	}

	// Point CODY_BIN at a non-existent path so the FIXED artifact takes the
	// honest-error path. A bluffing (pre-fix) artifact ignores the binary and
	// fabricates a "Cody: x" reply regardless → the assertion below FAILs.
	t.Setenv("CODY_BIN", filepath.Join(t.TempDir(), "does-not-exist-cody"))

	c := New()
	ctx := context.Background()

	res, err := c.chat(ctx, map[string]interface{}{"message": "x"})
	if err != nil {
		return // FIXED artifact: honest error — bluff is gone.
	}
	m, _ := res.(map[string]interface{})
	reply, _ := m["response"].(string)
	t.Fatalf("D17 BLUFF PINNED: Cody.chat returned %q without exec-ing a real cody binary (BLUFF-001).", reply)
}
