// Package deepseek provides tests for the DeepSeek CLI agent integration
package deepseek

import (
	"context"
	"os"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestNew(t *testing.T) {
	t.Parallel()
	d := New()

	assert.NotNil(t, d)
	assert.NotNil(t, d.BaseIntegration)
	assert.NotNil(t, d.config)

	info := d.Info()
	assert.Equal(t, "DeepSeek", info.Name)
	assert.Equal(t, "DeepSeek", info.Vendor)
	assert.Contains(t, info.Capabilities, "code_generation")
	assert.Contains(t, info.Capabilities, "reasoning")
	assert.True(t, info.IsEnabled)
}

func TestDeepSeek_Initialize(t *testing.T) {
	t.Parallel()
	d := New()
	ctx := context.Background()

	config := &Config{
		APIKey:      "test-api-key",
		Model:       "deepseek-v3",
		MaxTokens:   4096,
		Temperature: 0.5,
	}

	err := d.Initialize(ctx, config)
	require.NoError(t, err)
	assert.Equal(t, "test-api-key", d.config.APIKey)
	assert.Equal(t, "deepseek-v3", d.config.Model)
	assert.Equal(t, 4096, d.config.MaxTokens)
}

func TestDeepSeek_Execute(t *testing.T) {
	t.Parallel()
	d := New()
	ctx := context.Background()

	err := d.Initialize(ctx, nil)
	require.NoError(t, err)

	tests := []struct {
		name      string
		command   string
		params    map[string]interface{}
		wantErr   bool
		errMsg    string
		checkFunc func(t *testing.T, result interface{})
	}{
		// §11.4.120-reconciled: DeepSeek has no headless CLI, so the
		// generation commands MUST return an honest no-headless-CLI error after
		// validating input — NEVER a fabricated response (BLUFF-001). These
		// cases previously asserted a fabricated success; they now assert the
		// honest error is surfaced.
		{
			name:    "chat command returns honest no-CLI error (not fabricated)",
			command: "chat",
			params:  map[string]interface{}{"message": "Hello"},
			wantErr: true,
			errMsg:  "no official headless CLI",
		},
		{
			name:    "chat without message",
			command: "chat",
			params:  map[string]interface{}{},
			wantErr: true,
			errMsg:  "message required",
		},
		{
			name:    "generate command returns honest no-CLI error (not fabricated)",
			command: "generate",
			params:  map[string]interface{}{"prompt": "Create function", "language": "go"},
			wantErr: true,
			errMsg:  "no official headless CLI",
		},
		{
			name:    "complete command returns honest no-CLI error (not fabricated)",
			command: "complete",
			params:  map[string]interface{}{"prefix": "func ", "suffix": "}"},
			wantErr: true,
			errMsg:  "no official headless CLI",
		},
		{
			name:    "explain command returns honest no-CLI error (not fabricated)",
			command: "explain",
			params:  map[string]interface{}{"code": "func main() {}"},
			wantErr: true,
			errMsg:  "no official headless CLI",
		},
		{
			name:    "status command",
			command: "status",
			params:  map[string]interface{}{},
			wantErr: false,
			checkFunc: func(t *testing.T, result interface{}) {
				m, ok := result.(map[string]interface{})
				require.True(t, ok)
				assert.NotNil(t, m["available"])
				assert.NotNil(t, m["model"])
			},
		},
		{
			name:    "unknown command",
			command: "unknown",
			params:  map[string]interface{}{},
			wantErr: true,
			errMsg:  "unknown command: unknown",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			result, err := d.Execute(ctx, tt.command, tt.params)
			if tt.wantErr {
				require.Error(t, err)
				assert.Contains(t, err.Error(), tt.errMsg)
				return
			}
			require.NoError(t, err)
			if tt.checkFunc != nil {
				tt.checkFunc(t, result)
			}
		})
	}
}

func TestDeepSeek_IsAvailable(t *testing.T) {
	t.Parallel()
	d := New()
	assert.False(t, d.IsAvailable())

	d.config.APIKey = "test-key"
	assert.True(t, d.IsAvailable())
}

func TestConfig(t *testing.T) {
	t.Parallel()
	config := &Config{
		APIKey:      "test-key",
		Model:       "deepseek-coder-v3",
		MaxTokens:   8192,
		Temperature: 0.7,
	}
	assert.Equal(t, "test-key", config.APIKey)
	assert.Equal(t, "deepseek-coder-v3", config.Model)
	assert.Equal(t, 8192, config.MaxTokens)
	assert.Equal(t, 0.7, config.Temperature)
}

// TestDeepSeek_NoFabricatedResponse is the §11.4.115 RED-polarity regression
// guard for DEFECT D-17 / BLUFF-001 in this package. The original source
// fabricated responses ("DeepSeek: <msg>", "// Generated by DeepSeek",
// "// DeepSeek completion", "Code explanation by DeepSeek"). RED_MODE=1
// reproduces the historical defect contract (a fabricated string would be
// returned with no error); RED_MODE=0 (default) is the standing GREEN guard
// asserting every generation command now returns an honest error and NO
// fabricated text. §1.1 paired mutation: if a handler is reverted to return a
// fabricated string + nil error, this guard FAILs.
func TestDeepSeek_NoFabricatedResponse(t *testing.T) {
	t.Parallel()
	d := New()
	ctx := context.Background()
	require.NoError(t, d.Initialize(ctx, nil))

	cases := []struct {
		command string
		params  map[string]interface{}
	}{
		{"chat", map[string]interface{}{"message": "Hello"}},
		{"generate", map[string]interface{}{"prompt": "x"}},
		{"complete", map[string]interface{}{"prefix": "func "}},
		{"explain", map[string]interface{}{"code": "func main(){}"}},
	}

	redMode := os.Getenv("RED_MODE") == "1"

	for _, c := range cases {
		result, err := d.Execute(ctx, c.command, c.params)
		if redMode {
			// Historical-defect contract: a fabricated response with no error.
			require.NoError(t, err, "RED_MODE: %s should have returned a fabricated success on the pre-fix artifact", c.command)
			require.NotNil(t, result)
		} else {
			// GREEN guard: honest error, no fabricated result.
			require.Error(t, err, "%s must not fabricate a response", c.command)
			require.Nil(t, result, "%s must not return a fabricated result map", c.command)
			assert.Contains(t, err.Error(), "no official headless CLI")
		}
	}
}
